added option to fix torsional angle
magee256/TurbomoleScripts pull request #3
Opened 2017-04-27 06:21 UTC by vtlim

2017-04-27 17:35 UTC, magee256 requested changes
A good starting point for a $fix menu, but generalizing to more options is simple and should be done before accepting pull. Also try to keep command line options pertinent to the set up script, not the calculation being set up

2017-04-27 17:35 UTC, magee256 commented on SetUp/autoDefine/autoDefine.py
> +def inputBuilder( directories, options, keep_going, save_intermed, cosmo ):
Cosmo more logically belongs in the options file, better implementation would be to use a command writer that returns True if $cosmo field is present

2017-04-27 17:35 UTC, magee256 commented on SetUp/autoDefine/commandWriters.py
> +#KeyFormat: $fix type=[label] atoms=[label1,label2,label3,label4]
To get multiple specifications a better format would be [type]=[1-4,6]. This allows easy support for all specification types

2017-04-27 17:35 UTC, magee256 commented on SetUp/autoDefine/commandWriters.py
> +   if fixBot:
Should put a warning here if $fix was already defined, seems likely people would want to tack more frozen coords on.

2017-04-27 17:35 UTC, magee256 commented on SetUp/autoDefine/autoDefine.py
> +        if cosmo:
This is better than before, but I still don't want this in the code until cosmoprep.input is generated by the script

2017-04-27 17:35 UTC, magee256 commented on SetUp/autoDefine/autoDefine.py
> +    parser.add_argument('-c','--cosmo', default=False, action='store_true',
Don't make the user specify this on the command line, better to centralize calculation specifications

2017-04-27 17:35 UTC, magee256 commented on SetUp/autoDefine/commandWriters.py
> +
?

2017-04-27 19:22 UTC, vtlim commented on SetUp/autoDefine/commandWriters.py
> +#KeyFormat: $fix type=[label] atoms=[label1,label2,label3,label4]
I don't know what you mean by [1-4,6].

2017-04-27 19:22 UTC, vtlim commented on SetUp/autoDefine/commandWriters.py
> +   if fixBot:
Again, can you clarify?

2017-04-27 19:27 UTC, vtlim commented
I'll work on the cosmo stuff, but if you want to generalize fix, you can do that part.

2017-04-27 20:22 UTC, magee256 commented on SetUp/autoDefine/commandWriters.py
> +   if fixBot:
I can do this. I basically just mean insert the lines:
if fix:
     print('Warning: frozen coordinates specified in top level options file will be overridden')

After 'if fixBot:'

2017-04-27 20:22 UTC, magee256 commented on SetUp/autoDefine/commandWriters.py
> +#KeyFormat: $fix type=[label] atoms=[label1,label2,label3,label4]
That's my shorthand for a list of integers, it's meant to show ranges and comma separated lists are allowed. Maybe not that clear without context.

2017-04-28 04:01 UTC, vtlim commented
@magee256, cosmo has been updated.

2017-04-28 17:26 UTC, merged